// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: depot/cloud/v2/machine.proto

package cloudv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterMachineResponse_Kind int32

const (
	RegisterMachineResponse_KIND_UNSPECIFIED    RegisterMachineResponse_Kind = 0
	RegisterMachineResponse_KIND_BUILDKIT       RegisterMachineResponse_Kind = 1
	RegisterMachineResponse_KIND_GITHUB_ACTIONS RegisterMachineResponse_Kind = 2
	RegisterMachineResponse_KIND_PENDING        RegisterMachineResponse_Kind = 3
)

// Enum value maps for RegisterMachineResponse_Kind.
var (
	RegisterMachineResponse_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_BUILDKIT",
		2: "KIND_GITHUB_ACTIONS",
		3: "KIND_PENDING",
	}
	RegisterMachineResponse_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":    0,
		"KIND_BUILDKIT":       1,
		"KIND_GITHUB_ACTIONS": 2,
		"KIND_PENDING":        3,
	}
)

func (x RegisterMachineResponse_Kind) Enum() *RegisterMachineResponse_Kind {
	p := new(RegisterMachineResponse_Kind)
	*p = x
	return p
}

func (x RegisterMachineResponse_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterMachineResponse_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_depot_cloud_v2_machine_proto_enumTypes[0].Descriptor()
}

func (RegisterMachineResponse_Kind) Type() protoreflect.EnumType {
	return &file_depot_cloud_v2_machine_proto_enumTypes[0]
}

func (x RegisterMachineResponse_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterMachineResponse_Kind.Descriptor instead.
func (RegisterMachineResponse_Kind) EnumDescriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{1, 0}
}

type RegisterMachineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Types that are assignable to Cloud:
	//	*RegisterMachineRequest_Aws
	Cloud isRegisterMachineRequest_Cloud `protobuf_oneof:"cloud"`
}

func (x *RegisterMachineRequest) Reset() {
	*x = RegisterMachineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cloud_v2_machine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMachineRequest) ProtoMessage() {}

func (x *RegisterMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cloud_v2_machine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMachineRequest.ProtoReflect.Descriptor instead.
func (*RegisterMachineRequest) Descriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterMachineRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (m *RegisterMachineRequest) GetCloud() isRegisterMachineRequest_Cloud {
	if m != nil {
		return m.Cloud
	}
	return nil
}

func (x *RegisterMachineRequest) GetAws() *RegisterMachineRequest_AWSRegistration {
	if x, ok := x.GetCloud().(*RegisterMachineRequest_Aws); ok {
		return x.Aws
	}
	return nil
}

type isRegisterMachineRequest_Cloud interface {
	isRegisterMachineRequest_Cloud()
}

type RegisterMachineRequest_Aws struct {
	Aws *RegisterMachineRequest_AWSRegistration `protobuf:"bytes,2,opt,name=aws,proto3,oneof"`
}

func (*RegisterMachineRequest_Aws) isRegisterMachineRequest_Cloud() {}

type RegisterMachineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineId string `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are assignable to Task:
	//	*RegisterMachineResponse_Pending
	//	*RegisterMachineResponse_Buildkit
	//	*RegisterMachineResponse_GithubActions
	Task isRegisterMachineResponse_Task `protobuf_oneof:"task"`
}

func (x *RegisterMachineResponse) Reset() {
	*x = RegisterMachineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cloud_v2_machine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMachineResponse) ProtoMessage() {}

func (x *RegisterMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cloud_v2_machine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMachineResponse.ProtoReflect.Descriptor instead.
func (*RegisterMachineResponse) Descriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMachineResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *RegisterMachineResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (m *RegisterMachineResponse) GetTask() isRegisterMachineResponse_Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (x *RegisterMachineResponse) GetPending() *RegisterMachineResponse_PendingTask {
	if x, ok := x.GetTask().(*RegisterMachineResponse_Pending); ok {
		return x.Pending
	}
	return nil
}

func (x *RegisterMachineResponse) GetBuildkit() *RegisterMachineResponse_BuildKitTask {
	if x, ok := x.GetTask().(*RegisterMachineResponse_Buildkit); ok {
		return x.Buildkit
	}
	return nil
}

func (x *RegisterMachineResponse) GetGithubActions() *RegisterMachineResponse_GitHubActionsTask {
	if x, ok := x.GetTask().(*RegisterMachineResponse_GithubActions); ok {
		return x.GithubActions
	}
	return nil
}

type isRegisterMachineResponse_Task interface {
	isRegisterMachineResponse_Task()
}

type RegisterMachineResponse_Pending struct {
	Pending *RegisterMachineResponse_PendingTask `protobuf:"bytes,3,opt,name=pending,proto3,oneof"`
}

type RegisterMachineResponse_Buildkit struct {
	Buildkit *RegisterMachineResponse_BuildKitTask `protobuf:"bytes,4,opt,name=buildkit,proto3,oneof"`
}

type RegisterMachineResponse_GithubActions struct {
	GithubActions *RegisterMachineResponse_GitHubActionsTask `protobuf:"bytes,5,opt,name=github_actions,json=githubActions,proto3,oneof"`
}

func (*RegisterMachineResponse_Pending) isRegisterMachineResponse_Task() {}

func (*RegisterMachineResponse_Buildkit) isRegisterMachineResponse_Task() {}

func (*RegisterMachineResponse_GithubActions) isRegisterMachineResponse_Task() {}

type PingMachineHealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineId string `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
}

func (x *PingMachineHealthRequest) Reset() {
	*x = PingMachineHealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cloud_v2_machine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMachineHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMachineHealthRequest) ProtoMessage() {}

func (x *PingMachineHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cloud_v2_machine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMachineHealthRequest.ProtoReflect.Descriptor instead.
func (*PingMachineHealthRequest) Descriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{2}
}

func (x *PingMachineHealthRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type PingMachineHealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShouldTerminate bool `protobuf:"varint,1,opt,name=should_terminate,json=shouldTerminate,proto3" json:"should_terminate,omitempty"`
}

func (x *PingMachineHealthResponse) Reset() {
	*x = PingMachineHealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cloud_v2_machine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMachineHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMachineHealthResponse) ProtoMessage() {}

func (x *PingMachineHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cloud_v2_machine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMachineHealthResponse.ProtoReflect.Descriptor instead.
func (*PingMachineHealthResponse) Descriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{3}
}

func (x *PingMachineHealthResponse) GetShouldTerminate() bool {
	if x != nil {
		return x.ShouldTerminate
	}
	return false
}

type Cert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert string `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Cert) Reset() {
	*x = Cert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cloud_v2_machine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cert) ProtoMessage() {}

func (x *Cert) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cloud_v2_machine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cert.ProtoReflect.Descriptor instead.
func (*Cert) Descriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{4}
}

func (x *Cert) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *Cert) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RegisterMachineRequest_AWSRegistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Document  string `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *RegisterMachineRequest_AWSRegistration) Reset() {
	*x = RegisterMachineRequest_AWSRegistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cloud_v2_machine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMachineRequest_AWSRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMachineRequest_AWSRegistration) ProtoMessage() {}

func (x *RegisterMachineRequest_AWSRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cloud_v2_machine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMachineRequest_AWSRegistration.ProtoReflect.Descriptor instead.
func (*RegisterMachineRequest_AWSRegistration) Descriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RegisterMachineRequest_AWSRegistration) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *RegisterMachineRequest_AWSRegistration) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type RegisterMachineResponse_Mount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Device string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *RegisterMachineResponse_Mount) Reset() {
	*x = RegisterMachineResponse_Mount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cloud_v2_machine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMachineResponse_Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMachineResponse_Mount) ProtoMessage() {}

func (x *RegisterMachineResponse_Mount) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cloud_v2_machine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMachineResponse_Mount.ProtoReflect.Descriptor instead.
func (*RegisterMachineResponse_Mount) Descriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RegisterMachineResponse_Mount) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RegisterMachineResponse_Mount) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

// PendingTask represents an instruction to wait for a task to be assigned
type RegisterMachineResponse_PendingTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterMachineResponse_PendingTask) Reset() {
	*x = RegisterMachineResponse_PendingTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cloud_v2_machine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMachineResponse_PendingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMachineResponse_PendingTask) ProtoMessage() {}

func (x *RegisterMachineResponse_PendingTask) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cloud_v2_machine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMachineResponse_PendingTask.ProtoReflect.Descriptor instead.
func (*RegisterMachineResponse_PendingTask) Descriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{1, 1}
}

// BuildkitTask represents an instruction to start a buildkit daemon
type RegisterMachineResponse_BuildKitTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName string                           `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Cert       *Cert                            `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	CaCert     *Cert                            `protobuf:"bytes,3,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	Mounts     []*RegisterMachineResponse_Mount `protobuf:"bytes,4,rep,name=mounts,proto3" json:"mounts,omitempty"`
}

func (x *RegisterMachineResponse_BuildKitTask) Reset() {
	*x = RegisterMachineResponse_BuildKitTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cloud_v2_machine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMachineResponse_BuildKitTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMachineResponse_BuildKitTask) ProtoMessage() {}

func (x *RegisterMachineResponse_BuildKitTask) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cloud_v2_machine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMachineResponse_BuildKitTask.ProtoReflect.Descriptor instead.
func (*RegisterMachineResponse_BuildKitTask) Descriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{1, 2}
}

func (x *RegisterMachineResponse_BuildKitTask) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RegisterMachineResponse_BuildKitTask) GetCert() *Cert {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *RegisterMachineResponse_BuildKitTask) GetCaCert() *Cert {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *RegisterMachineResponse_BuildKitTask) GetMounts() []*RegisterMachineResponse_Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

// GithubActionsTask represents an instruction to start a GitHub Actions runner
type RegisterMachineResponse_GitHubActionsTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegistrationToken string `protobuf:"bytes,1,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url               string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Labels            string `protobuf:"bytes,4,opt,name=labels,proto3" json:"labels,omitempty"`
	RunnerVersion     string `protobuf:"bytes,5,opt,name=runner_version,json=runnerVersion,proto3" json:"runner_version,omitempty"`
}

func (x *RegisterMachineResponse_GitHubActionsTask) Reset() {
	*x = RegisterMachineResponse_GitHubActionsTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depot_cloud_v2_machine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMachineResponse_GitHubActionsTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMachineResponse_GitHubActionsTask) ProtoMessage() {}

func (x *RegisterMachineResponse_GitHubActionsTask) ProtoReflect() protoreflect.Message {
	mi := &file_depot_cloud_v2_machine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMachineResponse_GitHubActionsTask.ProtoReflect.Descriptor instead.
func (*RegisterMachineResponse_GitHubActionsTask) Descriptor() ([]byte, []int) {
	return file_depot_cloud_v2_machine_proto_rawDescGZIP(), []int{1, 3}
}

func (x *RegisterMachineResponse_GitHubActionsTask) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

func (x *RegisterMachineResponse_GitHubActionsTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterMachineResponse_GitHubActionsTask) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegisterMachineResponse_GitHubActionsTask) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *RegisterMachineResponse_GitHubActionsTask) GetRunnerVersion() string {
	if x != nil {
		return x.RunnerVersion
	}
	return ""
}

var File_depot_cloud_v2_machine_proto protoreflect.FileDescriptor

var file_depot_cloud_v2_machine_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x76, 0x32,
	0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xdf, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x4a, 0x0a, 0x03, 0x61, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x64,
	0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x57, 0x53, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x61, 0x77, 0x73, 0x1a, 0x4b, 0x0a, 0x0f, 0x41,
	0x57, 0x53, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x22, 0xfb, 0x06, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x4f, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x52, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x6b, 0x69, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x4b, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x00, 0x52, 0x08, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x6b, 0x69, 0x74, 0x12, 0x62, 0x0a, 0x0e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x39, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x69, 0x74, 0x48, 0x75, 0x62, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x33, 0x0a, 0x05, 0x4d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x1a, 0x0d, 0x0a, 0x0b, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x1a,
	0xcf, 0x01, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4b, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32,
	0x2e, 0x43, 0x65, 0x72, 0x74, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x63,
	0x61, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64,
	0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x65,
	0x72, 0x74, 0x52, 0x06, 0x63, 0x61, 0x43, 0x65, 0x72, 0x74, 0x12, 0x45, 0x0a, 0x06, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x65, 0x70,
	0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x06, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x1a, 0xa7, 0x01, 0x0a, 0x11, 0x47, 0x69, 0x74, 0x48, 0x75, 0x62, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x2d, 0x0a, 0x12, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x04, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x10, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x4b, 0x49, 0x54, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13,
	0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x47, 0x49, 0x54, 0x48, 0x55, 0x42, 0x5f, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x50, 0x45,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22,
	0x39, 0x0a, 0x18, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x19, 0x50, 0x69,
	0x6e, 0x67, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x68, 0x6f, 0x75, 0x6c,
	0x64, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x22, 0x2c, 0x0a, 0x04, 0x43, 0x65, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x32, 0xe2, 0x01, 0x0a, 0x0e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x64, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x26, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x6a, 0x0a, 0x11, 0x50, 0x69, 0x6e,
	0x67, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x28,
	0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x74,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0xbd, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x65,
	0x70, 0x6f, 0x74, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x32, 0x42, 0x0c, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x74, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2f, 0x76, 0x32, 0x3b, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x76, 0x32, 0xa2, 0x02, 0x03,
	0x44, 0x43, 0x58, 0xaa, 0x02, 0x0e, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x2e, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x56, 0x32, 0xca, 0x02, 0x0e, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x5c, 0x56, 0x32, 0xe2, 0x02, 0x1a, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x5c, 0x43, 0x6c,
	0x6f, 0x75, 0x64, 0x5c, 0x56, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x10, 0x44, 0x65, 0x70, 0x6f, 0x74, 0x3a, 0x3a, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x3a, 0x3a, 0x56, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_depot_cloud_v2_machine_proto_rawDescOnce sync.Once
	file_depot_cloud_v2_machine_proto_rawDescData = file_depot_cloud_v2_machine_proto_rawDesc
)

func file_depot_cloud_v2_machine_proto_rawDescGZIP() []byte {
	file_depot_cloud_v2_machine_proto_rawDescOnce.Do(func() {
		file_depot_cloud_v2_machine_proto_rawDescData = protoimpl.X.CompressGZIP(file_depot_cloud_v2_machine_proto_rawDescData)
	})
	return file_depot_cloud_v2_machine_proto_rawDescData
}

var file_depot_cloud_v2_machine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_depot_cloud_v2_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_depot_cloud_v2_machine_proto_goTypes = []interface{}{
	(RegisterMachineResponse_Kind)(0),                 // 0: depot.cloud.v2.RegisterMachineResponse.Kind
	(*RegisterMachineRequest)(nil),                    // 1: depot.cloud.v2.RegisterMachineRequest
	(*RegisterMachineResponse)(nil),                   // 2: depot.cloud.v2.RegisterMachineResponse
	(*PingMachineHealthRequest)(nil),                  // 3: depot.cloud.v2.PingMachineHealthRequest
	(*PingMachineHealthResponse)(nil),                 // 4: depot.cloud.v2.PingMachineHealthResponse
	(*Cert)(nil),                                      // 5: depot.cloud.v2.Cert
	(*RegisterMachineRequest_AWSRegistration)(nil),    // 6: depot.cloud.v2.RegisterMachineRequest.AWSRegistration
	(*RegisterMachineResponse_Mount)(nil),             // 7: depot.cloud.v2.RegisterMachineResponse.Mount
	(*RegisterMachineResponse_PendingTask)(nil),       // 8: depot.cloud.v2.RegisterMachineResponse.PendingTask
	(*RegisterMachineResponse_BuildKitTask)(nil),      // 9: depot.cloud.v2.RegisterMachineResponse.BuildKitTask
	(*RegisterMachineResponse_GitHubActionsTask)(nil), // 10: depot.cloud.v2.RegisterMachineResponse.GitHubActionsTask
}
var file_depot_cloud_v2_machine_proto_depIdxs = []int32{
	6,  // 0: depot.cloud.v2.RegisterMachineRequest.aws:type_name -> depot.cloud.v2.RegisterMachineRequest.AWSRegistration
	8,  // 1: depot.cloud.v2.RegisterMachineResponse.pending:type_name -> depot.cloud.v2.RegisterMachineResponse.PendingTask
	9,  // 2: depot.cloud.v2.RegisterMachineResponse.buildkit:type_name -> depot.cloud.v2.RegisterMachineResponse.BuildKitTask
	10, // 3: depot.cloud.v2.RegisterMachineResponse.github_actions:type_name -> depot.cloud.v2.RegisterMachineResponse.GitHubActionsTask
	5,  // 4: depot.cloud.v2.RegisterMachineResponse.BuildKitTask.cert:type_name -> depot.cloud.v2.Cert
	5,  // 5: depot.cloud.v2.RegisterMachineResponse.BuildKitTask.ca_cert:type_name -> depot.cloud.v2.Cert
	7,  // 6: depot.cloud.v2.RegisterMachineResponse.BuildKitTask.mounts:type_name -> depot.cloud.v2.RegisterMachineResponse.Mount
	1,  // 7: depot.cloud.v2.MachineService.RegisterMachine:input_type -> depot.cloud.v2.RegisterMachineRequest
	3,  // 8: depot.cloud.v2.MachineService.PingMachineHealth:input_type -> depot.cloud.v2.PingMachineHealthRequest
	2,  // 9: depot.cloud.v2.MachineService.RegisterMachine:output_type -> depot.cloud.v2.RegisterMachineResponse
	4,  // 10: depot.cloud.v2.MachineService.PingMachineHealth:output_type -> depot.cloud.v2.PingMachineHealthResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_depot_cloud_v2_machine_proto_init() }
func file_depot_cloud_v2_machine_proto_init() {
	if File_depot_cloud_v2_machine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_depot_cloud_v2_machine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMachineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cloud_v2_machine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMachineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cloud_v2_machine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMachineHealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cloud_v2_machine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMachineHealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cloud_v2_machine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cloud_v2_machine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMachineRequest_AWSRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cloud_v2_machine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMachineResponse_Mount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cloud_v2_machine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMachineResponse_PendingTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cloud_v2_machine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMachineResponse_BuildKitTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depot_cloud_v2_machine_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMachineResponse_GitHubActionsTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_depot_cloud_v2_machine_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RegisterMachineRequest_Aws)(nil),
	}
	file_depot_cloud_v2_machine_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*RegisterMachineResponse_Pending)(nil),
		(*RegisterMachineResponse_Buildkit)(nil),
		(*RegisterMachineResponse_GithubActions)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_depot_cloud_v2_machine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_depot_cloud_v2_machine_proto_goTypes,
		DependencyIndexes: file_depot_cloud_v2_machine_proto_depIdxs,
		EnumInfos:         file_depot_cloud_v2_machine_proto_enumTypes,
		MessageInfos:      file_depot_cloud_v2_machine_proto_msgTypes,
	}.Build()
	File_depot_cloud_v2_machine_proto = out.File
	file_depot_cloud_v2_machine_proto_rawDesc = nil
	file_depot_cloud_v2_machine_proto_goTypes = nil
	file_depot_cloud_v2_machine_proto_depIdxs = nil
}
