FROM --platform=$TARGETPLATFORM amazonlinux

ARG TARGETARCH
ARG BUILDKIT_VERSION=v0.11.6-depot.40
ARG BUILDKIT_PRIVATE_VERSION=v0.13.2-depot.10
ARG NYDUS_VERSION=v2.2.5
ARG MACHINE_AGENT_VERSION=v1.54.0
ARG CNI_VERSION=v1.4.0

RUN dnf upgrade -y && \
    dnf install -y htop wget git lsof fuse3 tar pigz e2fsprogs psmisc && \
    dnf clean all

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN mkdir -p /etc/buildkit && \
    curl -L "https://github.com/depot/buildkit/releases/download/${BUILDKIT_VERSION}/buildkit-${BUILDKIT_VERSION}.linux-${TARGETARCH}.tar.gz" | \
    tar -zxv -C /usr/bin --strip-components=1

RUN mkdir -p /opt/buildkit-private/bin && \
    curl -L "https://dl.depot.dev/buildkit-private/download/linux/$(uname -m)/${BUILDKIT_PRIVATE_VERSION}" | \
    tar -zxv -C /opt/buildkit-private/bin --strip-components=1

RUN mkdir -p /opt/nydus && \
    curl -L "https://github.com/dragonflyoss/nydus/releases/download/${NYDUS_VERSION}/nydus-static-${NYDUS_VERSION}-linux-${TARGETARCH}.tgz" | \
    tar -zxv -C /opt/nydus --strip-components=1 && \
    cp /opt/nydus/nydus* /usr/bin/


RUN curl -L "https://dl.depot.dev/machine-agent/download/linux/$(uname -m)/${MACHINE_AGENT_VERSION}" | \
    tar -zxv --strip-components=1 --directory /usr/bin bin/machine-agent

RUN mkdir -p /opt/cni/bin/ && \
    curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-linux-${TARGETARCH}-${CNI_VERSION}.tgz" | \
    tar -C /opt/cni/bin/ -zxv


# TODO: install vector
# TODO: binfmt/dagger engine
