name: release
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'dev-')
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Compute tag name
        id: tag-name
        run: echo "::set-output name=tag-name::${GITHUB_REF#refs/tags/}"
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          outputs: type=local,dest=dist/artifacts
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/artifacts/*
